<!DOCTYPE html>
<html lang="en">

<!-- The code below was generated by Chat GPT ans then edited. -->
<head>
    
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Explore Unofficial Holidays: A comprehensive database of fun and unique unofficial holidays.
    Learn about quirky celebrations and observances around the world.">
    <meta name="keywords" content="Unofficial holidays, unique celebrations, quirky observances, fun holidays, unusual days,
    special occasions">
    <meta name="author" content="Andrei Rogelio">

    <title>Unofficial Holidays Database</title>

    <!-- Style sheets area -->
    <link rel="stylesheet" href="holiday_styles.css">

    <!-- Icon for tabs / bookmarks -->  
    <link rel="icon" type="image/png" href="images/favicon.ico">

    <!-- Font links -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://googleapis.com/css2?family=Agbalumo&family=Open+Sans&display=swap" rel="stylesheet">

</head>

<body>

    <div class="wrapper">

        <div class="banner common">

            <div class="logo">
                <a href="index.php">
                    <img src="images/holidays_logo.png" alt="Holidays logo">
                </a>
            </div>  <!-- / logo -->

            <h1>Unofficial Holidays</h1>
        </div>  <!-- / banner -->

        <div class="nav common">

        <a href="show_all.php">Show_all</a>

        </div>  <!-- / nav -->

        <div class="main common">

        <h2>Welcome</h2>

        <p>
            Welcome to the world of unofficial holidays, a delightful and often quirky realm that celebrates unique and offbeat occasions!  Unofficial holidays, unlike their traditional counterparts, are not recognized by governments or institutions, yet they bring joy, creativity, and a sense of community to those who embrace them. 
        </p>

        <p>
            Unofficial holidays offer a delightful escape from the ordinary. Please use the search bar on the left hand side to explore this collection.  Not sure where to start?  Let us choose some random holidays to get the ball rolling.
        </p>    

        </div>  <!-- / main -->

        <div class="footer common">
        CC Mr Andrei Rogelio 2024
        </div>  <!-- / footer -->
    
    </div>  <!-- / wrapper -->

</body> 

</html>